question_data = [
    {
        "category": "Entertainment: Video Games",
        "type": "multiple",
        "difficulty": "medium",
        "question": "What is the punishment for playing Postal 2 in New Zealand?",
        "correct_answer": "10 years in prison and a fine of $50,000",
        "incorrect_answers": ["Fine of $5,000", "Nothing", "15 years in prison and a fine of $10,000"],
    },
    {
        "category": "Entertainment: Comics",
        "type": "multiple",
        "difficulty": "easy",
        "question": "Who is Batman?",
        "correct_answer": "Bruce Wayne",
        "incorrect_answers": ["Clark Kent", "Barry Allen", "Tony Stark"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "multiple",
        "difficulty": "hard",
        "question": "What was the name of the hero in the 80s animated video game &#039;Dragon&#039;s Lair&#039;?",
        "correct_answer": "Dirk the Daring",
        "incorrect_answers": ["Arthur", "Sir Toby Belch", "Guy of Gisbourne"],
    },
    {
        "category": "History",
        "type": "multiple",
        "difficulty": "easy",
        "question": "How many manned moon landings have there been?",
        "correct_answer": "6",
        "incorrect_answers": ["1", "3", "7"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "multiple",
        "difficulty": "hard",
        "question": "The Internet Meme &quot;All your base are belong to us&quot; is based on the poorly translated English Version of which Video Game?",
        "correct_answer": "Zero Wing",
        "incorrect_answers": ["F-Zero", "Wing Commander", "Star Wars: X-Wing"],
    },
    {
        "category": "Entertainment: Music",
        "type": "multiple",
        "difficulty": "easy",
        "question": "What is the best selling album of all time from 1976 to 2018?",
        "correct_answer": "Thriller",
        "incorrect_answers": ["Back in Black", "Abbey Road", "The Dark Side of the Moon"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "multiple",
        "difficulty": "easy",
        "question": "In the game Half-Life, which enemy is showcased as the final boss?",
        "correct_answer": "The Nihilanth",
        "incorrect_answers": ["Dr. Wallace Breen", "G-Man", "The Gonarch"],
    },
    {
        "category": "Vehicles",
        "type": "multiple",
        "difficulty": "medium",
        "question": "Which of the following is NOT a Russian car manufacturer?",
        "correct_answer": "BYD",
        "incorrect_answers": ["Silant", "Dragon", "GAZ"],
    },
    {
        "category": "Geography",
        "type": "multiple",
        "difficulty": "hard",
        "question": "What is the name of one of the Neo-Aramaic languages spoken by the Jewish population from Northwestern Iraq?",
        "correct_answer": "Lishana Deni",
        "incorrect_answers": ["Hulaul&aacute;", "Lishan Didan", "Chaldean Neo-Aramaic"],
    },
    {
        "category": "Entertainment: Music",
        "type": "multiple",
        "difficulty": "medium",
        "question": "Which of these is NOT the name of an album released by Miami-based producer DJ Khaled?",
        "correct_answer": "Don&#039;t Ever Play Yourself",
        "incorrect_answers": ["Major Key", "Suffering From Success", "I Changed A Lot"],
    },
    {
        "category": "Entertainment: Japanese Anime & Manga",
        "type": "multiple",
        "difficulty": "easy",
        "question": "What is the age of Ash Ketchum in Pokemon when he starts his journey?",
        "correct_answer": "10",
        "incorrect_answers": ["11", "12", "9"],
    },
    {
        "category": "Politics",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Denmark has a monarch.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "multiple",
        "difficulty": "easy",
        "question": "Who is the founder of Team Fortress 2&#039;s fictional company &quot;Mann Co&quot;?",
        "correct_answer": "Zepheniah Mann",
        "incorrect_answers": ["Cave Johnson", "Wallace Breem", "Saxton Hale"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "multiple",
        "difficulty": "easy",
        "question": "TF2: What code does Soldier put into the door keypad in &quot;Meet the Spy&quot;?",
        "correct_answer": "1111",
        "incorrect_answers": ["1432", "1337", "No code"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "multiple",
        "difficulty": "easy",
        "question": "In &quot;Fallout 4&quot; which faction is not present in the game?",
        "correct_answer": "The Enclave",
        "incorrect_answers": ["The Minutemen", "The Brotherhood of Steel", "The Institute"],
    },
    {
        "category": "Entertainment: Cartoon & Animations",
        "type": "multiple",
        "difficulty": "medium",
        "question": "Who is the &quot;dumb blonde&quot; character in Nickelodeon&#039;s &quot;The Loud House&quot;?",
        "correct_answer": "Leni",
        "incorrect_answers": ["Luan", "Luna", "Lincoln"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "multiple",
        "difficulty": "easy",
        "question": "In Danganronpa: Trigger Happy Havoc, what is the protagonist&#039;s name?",
        "correct_answer": "Makoto Naegi",
        "incorrect_answers": ["Hajime Hinata", "Nagito Komaeda", "Komaru Naegi"],
    },
    {
        "category": "Geography",
        "type": "multiple",
        "difficulty": "easy",
        "question": "What is the name of the peninsula containing Spain and Portugal?",
        "correct_answer": "Iberian Peninsula",
        "incorrect_answers": ["European Peninsula", "Peloponnesian Peninsula", "Scandinavian Peninsula"],
    },
    {
        "category": "History",
        "type": "multiple",
        "difficulty": "hard",
        "question": "The Hagia Sophia was commissioned by which emperor of the Byzantine Empire?",
        "correct_answer": "Justinian I",
        "incorrect_answers": ["Constantine IV", "Arcadius", "Theodosius the Great"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "multiple",
        "difficulty": "easy",
        "question": "In what year was the first &quot;Mass Effect&quot; game released?",
        "correct_answer": "2007",
        "incorrect_answers": ["2008", "2009", "2010"],
    },
    {
        "category": "Entertainment: Film",
        "type": "multiple",
        "difficulty": "medium",
        "question": "In The Lord of the Rings: The Fellowship of the Ring, which one of the following characters from the book was left out of the film?",
        "correct_answer": "Tom Bombadil",
        "incorrect_answers": ["Strider", "Barliman Butterbur", "Celeborn"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "multiple",
        "difficulty": "medium",
        "question": "Who voices the infamous Citadel Station A.I known as S.H.O.D.A.N, in the System Shock games?",
        "correct_answer": "Terri Brosius",
        "incorrect_answers": [" Jennifer Hale", "Jenn Taylor", "Lori Alan"],
    },
    {
        "category": "Vehicles",
        "type": "multiple",
        "difficulty": "easy",
        "question": "Which car tire manufacturer is famous for its &quot;P Zero&quot; line?",
        "correct_answer": "Pirelli",
        "incorrect_answers": ["Goodyear", "Bridgestone", "Michelin"],
    },
    {
        "category": "Entertainment: Books",
        "type": "multiple",
        "difficulty": "medium",
        "question": "In the novel &quot;Lord of the Rings&quot;, how many rings of power were given to the race of man?",
        "correct_answer": "9",
        "incorrect_answers": ["5", "11", "13"],
    },
    {
        "category": "Entertainment: Television",
        "type": "multiple",
        "difficulty": "medium",
        "question": "How many seasons did the TV show &quot;Donkey Kong Country&quot; last?",
        "correct_answer": "2",
        "incorrect_answers": ["1", "4", "5"],
    },
    {
        "category": "Entertainment: Music",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Scatman John&#039;s real name was John Paul Larkin.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Music",
        "type": "multiple",
        "difficulty": "medium",
        "question": "Which of these is NOT a song by Pegboard Nerds?",
        "correct_answer": "WiFi Tears",
        "incorrect_answers": ["Swamp Thing", "Emoji", "BAMF"],
    },
    {
        "category": "Entertainment: Japanese Anime & Manga",
        "type": "multiple",
        "difficulty": "easy",
        "question": "The two main characters of &quot;No Game No Life&quot;, Sora and Shiro, together go by what name?",
        "correct_answer": "Blank",
        "incorrect_answers": ["Immanity", "Disboard", "Warbeasts"],
    },
    {
        "category": "Entertainment: Japanese Anime & Manga",
        "type": "multiple",
        "difficulty": "hard",
        "question": "Medaka Kurokami from &quot;Medaka Box&quot; has what abnormality?",
        "correct_answer": "The End",
        "incorrect_answers": ["Perfection", "Sandbox", "Fairness"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "multiple",
        "difficulty": "easy",
        "question": "Who is the main protagonist in Danganronpa 2: Goodbye Despair?",
        "correct_answer": "Hajime Hinata",
        "incorrect_answers": ["Nagito Komaeda", "Makoto Naegi", "Junko Enoshima"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "multiple",
        "difficulty": "easy",
        "question": "When was the top-down online RPG &quot;Space Station 13&quot; released?",
        "correct_answer": "2003",
        "incorrect_answers": ["2000", "2010", "2006"],
    },
    {
        "category": "Science & Nature",
        "type": "multiple",
        "difficulty": "easy",
        "question": "What is the unit of electrical resistance?",
        "correct_answer": "Ohm",
        "incorrect_answers": ["Mho", "Tesla", "Joule"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "multiple",
        "difficulty": "hard",
        "question": "Which game in the &quot;Monster Hunter&quot; series introduced the &quot;Insect Glaive&quot; weapon?",
        "correct_answer": "Monster Hunter 4",
        "incorrect_answers": ["Monster Hunter Freedom", "Monster Hunter Stories", "Monster Hunter 2"],
    },
    {
        "category": "General Knowledge",
        "type": "multiple",
        "difficulty": "hard",
        "question": "Which product did Nokia, the telecommunications company, originally sell?",
        "correct_answer": "Paper",
        "incorrect_answers": ["Phones", "Computers", "Processors"],
    },
    {
        "category": "Entertainment: Music",
        "type": "multiple",
        "difficulty": "medium",
        "question": "Which rock band released the album &quot;The Bends&quot; in March 1995?",
        "correct_answer": "Radiohead",
        "incorrect_answers": ["Nirvana", "Coldplay", "U2"],
    },
    {
        "category": "General Knowledge",
        "type": "multiple",
        "difficulty": "easy",
        "question": "What is Tasmania?",
        "correct_answer": "An Australian State",
        "incorrect_answers": [
            "A flavor of Ben and Jerry&#039;s ice-cream",
            "A Psychological Disorder",
            "The Name of a Warner Brothers Cartoon Character",
        ],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "multiple",
        "difficulty": "medium",
        "question": "On which planet does the game Freedom Planet (2014) take place?",
        "correct_answer": "Avalice",
        "incorrect_answers": ["Freedom", "Galaxytrail", "Shang Mu"],
    },
    {
        "category": "Entertainment: Film",
        "type": "multiple",
        "difficulty": "medium",
        "question": "Which director directed the movie &quot;Pan&#039;s Labyrinth&quot;?",
        "correct_answer": "Guillermo Del Toro",
        "incorrect_answers": [
            "Alfonso Cuar&oacute;n",
            "Alejandro Gonz&aacute;lez I&ntilde;&aacute;rritu",
            " Alejandro Jodorowsky",
        ],
    },
    {
        "category": "Animals",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Tigers have one colour of skin despite the stripey fur.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Politics",
        "type": "multiple",
        "difficulty": "medium",
        "question": "Which former US president used &quot;Let&#039;s Make America Great Again&quot; as his campaign slogan before Donald Trump&#039;s campaign?",
        "correct_answer": "Ronald Reagan",
        "incorrect_answers": ["Jimmy Carter", "Gerald Ford", "Richard Nixon"],
    },
    {
        "category": "Mythology",
        "type": "multiple",
        "difficulty": "medium",
        "question": "Who is the god of war in Polynesian mythology?",
        "correct_answer": "&#039;Oro",
        "incorrect_answers": ["Hina", "Kohara", "M\u0101ui"],
    },
    {
        "category": "Sports",
        "type": "multiple",
        "difficulty": "hard",
        "question": "Which city features all of their professional sports teams&#039; jersey&#039;s with the same color scheme?",
        "correct_answer": "Pittsburgh",
        "incorrect_answers": ["New York", "Seattle", "Tampa Bay"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "multiple",
        "difficulty": "hard",
        "question": "In the game Warframe, what Mastery Rank do you need to have to build the Tigris Prime?",
        "correct_answer": "13",
        "incorrect_answers": ["6", "18", "10"],
    },
    {
        "category": "Science: Computers",
        "type": "multiple",
        "difficulty": "hard",
        "question": "What was the name of the first Bulgarian personal computer?",
        "correct_answer": "IMKO-1",
        "incorrect_answers": ["Pravetz 82", "Pravetz 8D", "IZOT 1030"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Mythology",
        "type": "multiple",
        "difficulty": "medium",
        "question": "Which greek god\/goddess tossed a golden apple with the words &quot;for the fairest&quot; into the middle of the feast of the gods?",
        "correct_answer": "Eris",
        "incorrect_answers": ["Hades", "Ares", "Artemis"],
    },
    {
        "category": "Entertainment: Television",
        "type": "multiple",
        "difficulty": "easy",
        "question": "Which of the following awards do Matt Stone and Trey Parker NOT have?",
        "correct_answer": "Oscar",
        "incorrect_answers": ["Emmy", "Tony", "Grammy"],
    },
    {
        "category": "Vehicles",
        "type": "multiple",
        "difficulty": "medium",
        "question": "Which of these cars is NOT considered one of the 5 Modern Supercars by Ferrari?",
        "correct_answer": "Testarossa",
        "incorrect_answers": ["Enzo Ferrari", "F40", "288 GTO"],
    },
    {
        "category": "Entertainment: Film",
        "type": "multiple",
        "difficulty": "easy",
        "question": "In the movie &quot;V for Vendetta,&quot; what is the date that masked vigilante &quot;V&quot; urges people to remember?",
        "correct_answer": "November 5th",
        "incorrect_answers": ["November 6th", "November 4th", "September 5th"],
    },
    {
        "category": "Entertainment: Film",
        "type": "multiple",
        "difficulty": "easy",
        "question": "The 1996 film &#039;Fargo&#039; is primarily set in which US state?",
        "correct_answer": "Minnesota",
        "incorrect_answers": ["North Dakota", "South Dakota", "Wisconsin"],
    },
]
